can't kill a thread, so I had to rewrite this as a process, so we can kill it, to possibly prevent a reactjs error this probably caused.
(It's fine to use a process, it's just that a thread is more light-weight so it's probably faster, etc)

Here's the error message of the error we sometimes get:

Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
at fs (http://localhost:8501/static/js/main.d090770a.js:2:2463724)
at ka (http://localhost:8501/static/js/main.d090770a.js:2:2435486)
at http://localhost:8501/static/js/7673.e016f6f7.chunk.js:2:369537
at http://localhost:8501/static/js/7673.e016f6f7.chunk.js:2:386316
at http://localhost:8501/static/js/7673.e016f6f7.chunk.js:2:321305
at http://localhost:8501/static/js/7673.e016f6f7.chunk.js:2:321516
at http://localhost:8501/static/js/7673.e016f6f7.chunk.js:2:317251
at http://localhost:8501/static/js/7673.e016f6f7.chunk.js:2:317498
at Is (http://localhost:8501/static/js/main.d090770a.js:2:2475460)
at t.unstable_runWithPriority (http://localhost:8501/static/js/main.d090770a.js:2:3255894)