This mimetype fix may not fix the wierd error, but it's probably necessary!
The error:

TransportError: Failed to retrieve

http://metadata.google.internal/computeMetadata/v1/universe/universe-domain from

the Google Compute Engine metadata service. Compute Engine Metadata server

unavailable due to HTTPConnectionPool(host='metadata.google.internal', port=80):

Max retries exceeded with url: /computeMetadata/v1/universe/universe-domain

(Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at

0x7fb5a16b3800>, 'Connection to metadata.google.internal timed out. (connect

timeout=120)'))